version: '3.8'

services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  app:
    platform: linux/x86_64
    depends_on:
      - mysqldb
    build: ./
    restart: unless-stopped
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes: 
  db: